### ISSUE TITLE
Cant install using setup.sh

### ISSUE THREAD

**Issue by ded5b13328** [possi/jas-profile#1]
Hey,

I tryed to clone and install via wget and get an Error.

ded5b13328@localhorst ~/> wget -O - https://raw.githubusercontent.com/possi/jas-profile/master/setup.sh | bash; # or
--2015-01-26 15:26:24--  https://raw.githubusercontent.com/possi/jas-profile/master/setup.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.31.17.133, 23.235.46.133, 185.31.18.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.31.17.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5089 (5.0K) [text/plain]
Saving to: `STDOUT'

100%[======================================================================================================================================================================================================================================>] 5,089       --.-K/s   in 0s

2015-01-26 15:26:25 (18.4 MB/s) - written to stdout [5089/5089]

Cloning into '/home/ded5b13328/.config/jas-profile'...
remote: Counting objects: 137, done.
remote: Total 137 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (137/137), 233.34 KiB | 348 KiB/s, done.
Resolving deltas: 100% (80/80), done.
/home/ded5b13328/.config/jas-profile/setup.sh: line 9: $'\r': command not found
/home/ded5b13328/.config/jas-profile/setup.sh: line 10: syntax error near unexpected token `$'{\r''
'home/ded5b13328/.config/jas-profile/setup.sh: line 10:`download () {
ded5b13328@localhorst ~/>

Any suggestions?!

**Comment by possi** [comment]
Maybe you're behind a proxy? Looks like the downloaded shell script is converted to windows file endings.
Have you tried curl as an alternative? Or the usual Setup (which is 3 then 1 command ;) )

**Comment by ded5b13328** [comment]
Solution: git config --global core.autocrlf input
(anything else then true)
